### ISSUE TITLE
A little bug

### ISSUE THREAD

**Issue by VectoridEverlast** [Songs-of-War/Songs-of-War-Launcher#92] opened 2021-05-07 20:04 UTC
```
TypeError: result.toFixed is not a function
    at Object.dataValue (C:\Users\Vectorid\AppData\Local\Programs\songs-of-war-launcher\resources\app.asar\node_modules\wmic-sys-info\lib\helpers.js:31:17)
    at C:\Users\Vectorid\AppData\Local\Programs\songs-of-war-launcher\resources\app.asar\node_modules\wmic-sys-info\index.js:75:29
    at ChildProcess.exithandler (child_process.js:303:7)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```

---

Songs of War Game 1.10.7
Electron 11.4.2
win32 10.0.19042
Locale: en-US

**Comment by eDexiam** [comment] 2021-05-15 10:25
Duplicate of #93

**Closed by eDexiam** 2021-05-15 10:25 UTC
