### ISSUE TITLE
I get this message when I open the Launcher

### ISSUE THREAD

**Issue by Uthri** [Songs-of-War/Songs-of-War-Launcher#142] opened 2021-10-01 20:05 UTC
```
TypeError: Cannot read property 'getServer' of null
    at refreshServerStatus (file:///C:/Users/brand/AppData/Local/Programs/songs-of-war-launcher/resources/app.asar/app/assets/js/scripts/landing.js:255:49)
    at file:///C:/Users/brand/AppData/Local/Programs/songs-of-war-launcher/resources/app.asar/app/assets/js/scripts/landing.js:343:46
```

---

Songs of War Game 2.0.0-alpha2
Electron 13.3.0
win32 10.0.19042
Locale: en-US

**Comment by eDexiam** [comment] 2021-10-02 22:18
Duplicate of #140

**Closed by eDexiam** 2021-10-02 22:18 UTC
