### ISSUE TITLE
Please Help Me

### ISSUE THREAD

**Issue by HMoulikN** [Songs-of-War/Songs-of-War-Launcher#174] opened 2022-01-15 10:56 UTC
```
TypeError: Cannot read property 'getServer' of null
    at refreshServerStatus (file:///C:/Users/hmpla/AppData/Local/Programs/songs-of-war-launcher/resources/app.asar/app/assets/js/scripts/landing.js:284:49)
    at file:///C:/Users/hmpla/AppData/Local/Programs/songs-of-war-launcher/resources/app.asar/app/assets/js/scripts/landing.js:372:46
```

---

Songs of War Game 1.10.16
Electron 13.6.3
win32 10.0.19044
Locale: en-US

**Comment by eDexiam** [comment] 2022-02-13 15:24
Duplicate of #140

**Closed by eDexiam** 2022-02-13 15:24 UTC
