### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by TTVTeardrop** [Songs-of-War/Songs-of-War-Launcher#141] opened 2021-10-01 00:08 UTC
```
TypeError: Cannot read property 'getServer' of null
    at refreshServerStatus (file:///C:/Users/User/AppData/Local/Programs/songs-of-war-launcher/resources/app.asar/app/assets/js/scripts/landing.js:284:49)
    at file:///C:/Users/User/AppData/Local/Programs/songs-of-war-launcher/resources/app.asar/app/assets/js/scripts/landing.js:372:46
```

---

Songs of War Game 1.10.14
Electron 12.1.0
win32 10.0.19043
Locale: en-US

**Comment by eDexiam** [comment] 2021-10-02 22:18
Duplicate of #140

**Closed by eDexiam** 2021-10-02 22:18 UTC
