### ISSUE TITLE
this happens when i open the launcher

### ISSUE THREAD

**Issue by Selphie1** [Songs-of-War/Songs-of-War-Launcher#101] opened 2021-06-13 09:48 UTC
```
TypeError: result.toFixed is not a function
    at Object.dataValue (C:\Users\HP\AppData\Local\Programs\songs-of-war-launcher\resources\app.asar\node_modules\wmic-sys-info\lib\helpers.js:31:17)
    at C:\Users\HP\AppData\Local\Programs\songs-of-war-launcher\resources\app.asar\node_modules\wmic-sys-info\index.js:75:29
    at ChildProcess.exithandler (child_process.js:308:7)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
```

---

Songs of War Game 1.10.12
Electron 12.0.7
win32 10.0.19041
Locale: en-US

**Comment by eDexiam** [comment] 2021-06-13 10:06
Duplicate of #89

**Closed by eDexiam** 2021-06-13 10:06 UTC
