### ISSUE TITLE
i am getting this error

### ISSUE THREAD

**Issue by silentsensei** [Songs-of-War/Songs-of-War-Launcher#163] opened 2021-11-16 07:47 UTC
```
TypeError: Cannot read property 'getServer' of null
    at refreshServerStatus (file:///C:/Users/prady/AppData/Local/Programs/songs-of-war-launcher/resources/app.asar/app/assets/js/scripts/landing.js:255:49)
    at file:///C:/Users/prady/AppData/Local/Programs/songs-of-war-launcher/resources/app.asar/app/assets/js/scripts/landing.js:343:46
```

---

Songs of War Game 2.0.0-alpha4
Electron 13.6.1
win32 10.0.19042
Locale: en-US

**Comment by eDexiam** [comment] 2022-02-13 15:24
Duplicate of #140

**Closed by eDexiam** 2022-02-13 15:24 UTC
