### ISSUE TITLE
Illegal operation on a directory yay

### ISSUE THREAD

**Issue by Pythonesc** [Songs-of-War/Songs-of-War-Launcher#114] opened 2021-07-28 21:49 UTC
```
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:592:3)
    at tryReadSync (fs.js:366:20)
    at Object.readFileSync (fs.js:403:19)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8643)
    at FSWatcher.<anonymous> (file:///C:/Users/Juuso/AppData/Local/Programs/Songs-of-War-Launcher/resources/app.asar/app/assets/js/scripts/landing.js:1338:102)
    at FSWatcher.emit (events.js:315:20)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:186:12)
```

---

Songs of War Game 1.10.13-alpha2
Electron 12.0.11
win32 10.0.19043
Locale: en-GB

**Comment by eDexiam** [comment] 2021-08-10 00:41
The fix for this seems to be running the launcher as administrator, for whatever reason windows is denying access to the launcher files.

**Comment by eDexiam** [comment] 2022-09-11 09:35
Could not reproduce since

**Closed by eDexiam** 2022-09-11 09:35 UTC
Labels: help wanted
